articlesPerPage: 10
fetchWeeks: 1
repo: github.com/jbowdre/chillfeed
feeds:
  - url: http://krebsonsecurity.com/feed/
  - url: http://whatever.scalzi.com/feed/
  - url: http://www.schneier.com/blog/index.rdf
  - url: http://xkcd.com/rss.xml
  - url: https://alexandrawolfe.ca/feed/
  - url: https://about.gitlab.com/security-releases.xml
  - url: https://austinross.xyz/rss.xml
  - url: https://binarydigit.cafe/feed/
  - url: https://blog.autumnrain.cc/rss.xml
  - url: https://blog.controld.com/rss/
  - url: https://blog.jbowdre.lol/feed/
  - url: https://boehs.org/in/blog.xml
  - url: https://bunny.net/blog/rss/
  - url: https://citationneeded.news/rss/
  - url: https://cool-as-heck.blog/index.xml
  - url: https://crankysec.com/feed/feed.xml
  - url: https://doublepulsar.com/feed
  - url: https://edfishjr.com/feed/
  - url: https://feedpress.me/coryd
  - url: https://frills.dev/rss.xml
  - url: https://gkeenan.co/avgb?format=rss
  - url: https://grahamhelton.com/blog/index.xml
  - url: https://hamvocke.com/feed.xml
    title: Ham Vocke
  - url: https://home-assistant.io/atom.xml
  - url: https://immich.app/blog/rss.xml
  - url: https://journal.paoloamoroso.com/feed/
  - url: https://jvns.ca/atom.xml
  - url: https://kmcd.dev/posts/index.xml
  - url: https://lewisdale.dev/feed/
  - url: https://louplummer.lol/feed.atom
  - url: https://medium.com/feed/hashicorp-engineering
  - url: https://melkat.blog/rss.xml
  - url: https://newsletter.goodtechthings.com/feed
  - url: https://notes.jeddacp.com/feed/
  - url: https://obsidian.md/feed.xml
  - url: https://omglol.news/feed.json
  - url: https://opentofu.org/blog/rss.xml
  - url: https://pluralistic.net/feed/
  - url: https://rknight.me/subscribe/posts/rss.xml
  - url: https://rscottjones.com/feed/
  - url: https://runtimeterror.dev/feed.xml
  - url: https://saltproject.io/blog/index.xml
  - url: https://seirdy.one/posts/atom.xml
  - url: https://simplex.chat/feed.rss
  - url: https://snikket.org/blog/index.xml
  - url: https://stuffandthings.lol/feed.xml
  - url: https://tailscale.com/blog/index.xml
  - url: https://tailscale.dev/feed.xml
  - url: https://thedent.net/feed.atom
  - url: https://that-bloke.com/feed/
  - url: https://world.hey.com/corlin/feed.atom
  - url: https://www.fastmail.com/feed/
  - url: https://www.hashicorp.com/blog/feed.xml
  - url: https://www.lastweekinaws.com/feed/